load("@prysm//tools/go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "block.go",
        "block_execution.go",
        "endpoints_beacon.go",
        "endpoints_blob.go",
        "endpoints_config.go",
        "endpoints_debug.go",
        "endpoints_events.go",
        "endpoints_lightclient.go",
        "endpoints_node.go",
        "endpoints_rewards.go",
        "endpoints_validator.go",
        "other.go",
        "state.go",
    ],
    importpath = "github.com/OffchainLabs/prysm/v7/api/shared/structs",
    visibility = ["//visibility:public"],
    deps = [
        "//consensus-types/primitives:go_default_library",
    ],
)





